---

# To run: ansible-playbook -v -i localhost, deploy.yml

- hosts: 127.0.0.1
  connection: local
  sudo: false
  gather_facts: true
  vars_files:
    - "src/config/secrets.yml"
    - "src/config/vars.yml"
  tasks:

  # Common base resources

  - name: Create database and other base resources
    cloudformation:
      stack_name: "{{ deployment_id }}-base"
      state: "present"
      region: "{{ aws_region }}"
      template: "src/cloudformation-templates/base.template"
      template_parameters:
        DeploymentName: "{{ deployment_id }}"
    register: base_stack
    tags:
      - base

  - debug: var=base_stack.stack_outputs
    tags:
      - base

  - name: Create S3 buckets
    s3: bucket={{ item }} mode=create region={{ aws_region }}
    with_items:
      - "{{ s3_artifactory_bucket }}"
      - "{{ s3_data_bucket }}"
    tags:
      - base

  # Lambda functions

  - name: Clean common build directory
    file: path={{ build_path }} state=absent

  - name: Create common build directories
    file: path={{ item }} state=directory mode=0755
    with_items:
      - "{{ build_path }}"
      - "{{ build_path }}/interfaces"
      - "{{ build_path }}/artifacts"

  - name: Configure function
    template: src=src/functions/{{ item }}/config.js.j2 dest=src/functions/{{ item }}/config.js mode=0644
    with_items: functions

  - name: Package Lambda functions
    command: zip -FSr ../../../{{ build_path }}/artifacts/{{ item }}.zip . -i *
    args:
      chdir: src/functions/{{ item }}
    with_items: functions

  - name: Sync packages to S3 artifactory
    command: aws s3 cp {{ build_path }}/artifacts s3://{{ s3_artifactory_bucket }}/artifacts/ --recursive --region {{ aws_region }}

  - name: Create Lambda functions
    cloudformation:
      stack_name: "{{ deployment_id }}-lambdas"
      state: present
      region: "{{ aws_region }}"
      template: src/cloudformation-templates/functions.template
      template_parameters:
        DeploymentName: "{{ deployment_id }}"
        ArtifactoryBucket: "{{ s3_artifactory_bucket }}"
    register: lambda_stack

  - name: Print Lambda function ARNs
    debug: var=lambda_stack.stack_outputs

  - name: Reconfigure functions to use the latest code
    command: >
      aws lambda update-function-code 
      --function-name {{ lambda_stack.stack_outputs.get(item) }}
      --s3-bucket {{ s3_artifactory_bucket }} 
      --s3-key artifacts/{{ item }}.zip
    with_items: functions

  # Lambda DynamoDB Stream handler setup

  - name: Create DynamoDB Stream
    command: >
      aws dynamodb update-table 
      --table-name {{ deployment_id }}
      --stream-specification StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES
    register: update_stream
    ignore_errors: yes

  - name: Describe DynamoDB table
    command: >
      aws dynamodb describe-table 
      --table-name {{ deployment_id }}
    register: stream_output

  - name: Parse DynamoDB configuration
    set_fact:
      dynamo_config: "{{ stream_output.stdout|from_json }}"

  - name: Configure Lambda function to read DynamoDB Stream
    command: >
      aws lambda create-event-source-mapping 
      --function-name {{ lambda_stack.stack_outputs.stalker }}
      --event-source-arn {{ dynamo_config.Table.LatestStreamArn }}
      --enabled
      --batch-size 100
      --starting-position TRIM_HORIZON
    when: update_stream|success

  # API Gateway interfaces

  - name: Configure interfaces
    template: src=src/interfaces/{{ item }}.yml.j2 dest={{ build_path }}/interfaces/{{ item }}.yml mode=0644
    with_items: interfaces

  - name: Create interfaces
    command: >
      ./aws-api-import.sh
      --profile {{ aws_cli_profile }}
      --create 
      --deploy {{ interface_stage }}
      ../../{{ build_path }}/interfaces/{{ item }}.yml
    args:
      chdir: "{{ swagger_importer_path }}"
    with_items: interfaces
    when: importer_mode == "create"
    register: importer_output

  - name: Print API URL (uneducated guess)
    debug: msg="https://{{ importer_output.results[0].stdout_lines[-1].split()[-4] }}.execute-api.{{ aws_region }}.amazonaws.com/{{ importer_output.results[0].stdout_lines[-1].split()[-1] }}/"
    when: importer_mode == "create"
    ignore_errors: yes

  - name: Update interface
    command: >
      ./aws-api-import.sh
      --profile {{ aws_cli_profile }}
      --update {{ interface_id }}
      --deploy {{ interface_stage }}
      ../../{{ build_path }}/interfaces/{{ interface_name }}.yml
    args:
      chdir: "{{ swagger_importer_path }}"
    when: importer_mode == "update"
    register: importer_output

  - name: Print API URL (uneducated guess)
    debug: msg="https://{{ importer_output.stdout_lines[-1].split()[-4] }}.execute-api.{{ aws_region }}.amazonaws.com/{{ importer_output.stdout_lines[-1].split()[-1] }}/"
    when: importer_mode == "update"
    ignore_errors: yes
