---

# The ID of your AWS Root account. Can be found under Account Settings, or on
# pretty much as part of any ARN you own.
aws_account_id: 000000000000

# Name of your AWS CLI profile for Swagger Importer
aws_cli_profile: myprofile

# Name of the S3 bucket where to store uploaded Lambda .zip files
s3_artifactory_bucket: mahbucket

# Name of the S3 bucket where to store application data
s3_data_bucket: mahbucket
