---

aws_region: eu-west-1
deployment_id: noinstances

# Lambda functions
functions:
  dynamocrud:
    foo: bar
  objectstore:
    baz: babar

# API Gateway interfaces
interfaces:
  main:
    foo: baz


# Advanced configuration, no need to edit these
build_path: build
swagger_importer_path: tools/aws-apigateway-swagger-importer
importer_mode: create
interface_stage: prod

arn_prefix_lambda: "arn:aws:apigateway:{{ aws_region }}:lambda:path/2015-03-31/functions/arn:aws:lambda:{{ aws_region }}:{{ aws_account_id }}:function:"
arn_prefix_role: "arn:aws:iam::{{ aws_account_id }}:role/"
