---

# To run: ansible-playbook -i localhost, cloudformation.yml

- hosts: 127.0.0.1
  connection: local
  sudo: false
  vars_files:
    - "vars.yml"
  tasks:
  - name: Create Cloudformation stack
    cloudformation:
      stack_name: "noinstances-{{ stack_base_name }}-data"
      state: "present"
      region: "{{ aws_region }}"
      template: "cloudformation-data.template"
      template_parameters:
        DeploymentName: "{{ stack_base_name }}"
      tags:
        DeploymentName: "{{ stack_base_name }}"
